export type CreateMahasiswaRequestDto = {
  nim: string;
  password: string;
  nama: string;
  email: string;
  telp?: string | null;
  foto?: string | null;
  image_public_id?: string | null;
  jurusan_id: number;
  // user_id is auto-generated by the repository when creating a mahasiswa
};

export type UpdateMahasiswaRequestDto = Partial<{
  nim: string;
  password: string;
  nama: string;
  email: string;
  telp: string | null;
  foto: string | null;
  image_public_id: string | null;
  jurusan_id: number;
}>;
